---
- name: create sys_user "{{ sys_user }}"
  user:
    name: "{{ sys_user }}"
    createhome: yes
    state: present

- name: Create doc root "{{ doc_root }}"
  file:
    path: "{{ doc_root }}"
    state: directory
    owner: "{{ sys_user }}"
    group: www-data
    mode: 0755

- name: Wait for no more running dpkg or apt processes
  shell: while pgrep '(dpkg|apt)' >/dev/null 2>&1; do sleep 1; done;
  tags: dpkg-lock

- name: Wait for lock files to be released
  shell: >
    while fuser /var/cache/apt/archives/lock
    /var/lib/apt/lists/lock/var/lib/apt/lists/lock
    /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1;
    done;
  tags: dpkg-lock

- name: Install software dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nginx
    - curl
    - zip
    - git
    - mysql-client
    - php7.0-fpm
    - php7.0-curl
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-xml
    - php7.0-xmlrpc
    - php7.0-mysql
